// <auto-generated />
namespace ToDo_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addTitleColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTitleColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291323564_addTitleColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
